//
// PullRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class PullRequest: JSONEncodable {
    public var id: Int32?
    public var title: String?
    public var user: Profile?
    public var body: String?
    public var createdAt: String?
    public var updatedAt: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["title"] = self.title
        nillableDictionary["user"] = self.user?.encodeToJSON()
        nillableDictionary["body"] = self.body
        nillableDictionary["created_at"] = self.createdAt
        nillableDictionary["updated_at"] = self.updatedAt
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
