//
// Repository.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Repository: JSONEncodable {
    public var id: Int32?
    public var name: String?
    public var fullName: String?
    public var description: String?
    public var forksCount: Int32?
    public var stargazersCount: Int32?
    public var owner: Profile?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["full_name"] = self.fullName
        nillableDictionary["description"] = self.description
        nillableDictionary["forks_count"] = self.forksCount?.encodeToJSON()
        nillableDictionary["stargazers_count"] = self.stargazersCount?.encodeToJSON()
        nillableDictionary["owner"] = self.owner?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
