//
// ResultResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ResultResponse: JSONEncodable {
    public var totalCount: Int32?
    public var items: [Repository]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["total_count"] = self.totalCount?.encodeToJSON()
        nillableDictionary["items"] = self.items?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
